"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import environ
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))

# .env 파일 로드
env.read_env(os.path.join(BASE_DIR, ".env"))

# 환경 변수 적용
SECRET_KEY = env("SECRET_KEY")  # 👈 여기서 오류가 나면 .env 파일을 못 읽은 것
DEBUG = env("DEBUG")  # 👈 'DUBUG' 오타 확인!
KAKAO_API_KEY = env('KAKAO_API_KEY')

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'project', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "main/region.db",
    },
    'soil': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "main/soil.db",
    },
    'climate': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "main/climate.db",
    },
    'cabbage': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/cabbage.db',
    },
    'onion': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/onion.db',
    },
    'access_cm2': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/ACCESS-CM2.db',
    },
    'access_esm1_5': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/ACCESS-ESM1-5.db',
    },
    'canesm5': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/CanESM5.db',
    },
    'cnrm_cm6_1': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/CNRM-CM6-1.db',
    },
    'cnrm_esm2_1': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/CNRM-ESM2-1.db',
    },
    'ec_earth3': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/EC-Earth3.db',
    },
    'gfdl_esm4': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/GFDL-ESM4.db',
    },
    'inm_cm4_8': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/INM-CM4-8.db',
    },
    'inm_cm5_0': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/INM-CM5-0.db',
    },
    'ipsl_cm6a_lr': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/IPSL-CM6A-LR.db',
    },
    'kace_1_0_g': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/KACE-1-0-G.db',
    },
    'miroc6': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/MIROC6.db',
    },
    'miroc_es2l': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/MIROC-ES2L.db',
    },
    'mpi_esm1_2_hr': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/MPI-ESM1-2-HR.db',
    },
    'mpi_esm1_2_lr': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/MPI-ESM1-2-LR.db',
    },
    'mri_esm2_0': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/MRI-ESM2-0.db',
    },
    'noresm2_lm': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/NorESM2-LM.db',
    },
    'ukesm1_0_ll': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main/databases/UKESM1-0-LL.db',
    },
}

DATABASE_ROUTERS = ['main.routers.MultiDBRouter']

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'project', 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
