# Generated by Django 5.1.6 on 2025-03-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('year', models.IntegerField(db_column='년', primary_key=True, serialize=False)),
                ('month', models.IntegerField(db_column='월')),
                ('sido', models.CharField(db_column='시도', max_length=100)),
                ('sigungu', models.CharField(db_column='시군구', max_length=100)),
                ('eupmyeondong', models.CharField(db_column='읍면동', max_length=100)),
                ('min_temp', models.FloatField(db_column='최저온도')),
                ('max_temp', models.FloatField(db_column='최고온도')),
                ('humidity', models.FloatField(db_column='습도')),
                ('wind_speed', models.FloatField(db_column='풍속')),
                ('solar_radiation', models.CharField(db_column='일사량', max_length=100)),
                ('cumulative_precipitation', models.CharField(db_column='누적강수량', max_length=100)),
                ('avg_precipitation', models.FloatField(db_column='평균강수량')),
                ('latitude', models.FloatField(db_column='위도')),
                ('longitude', models.FloatField(db_column='경도')),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
