# Generated by Django 5.1.6 on 2025-05-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_region'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='region',
            table='Region',
        ),
        migrations.AlterModelTable(
            name='weatherdata',
            table='Sheet1',
        ),
    ]
