# Generated by Django 5.1.6 on 2025-05-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_region_table_alter_weatherdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soildata',
            table='soildata',
        ),
    ]
