# Generated by Django 5.1.6 on 2025-06-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_soildata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabbage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_column='region', max_length=50)),
                ('year', models.IntegerField(db_column='year')),
                ('yield_per_10a', models.FloatField(db_column='yield_per_10a')),
                ('total_production', models.FloatField(db_column='total_production')),
            ],
            options={
                'db_table': 'cabbage_production',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_column='region', max_length=50)),
                ('year', models.IntegerField(db_column='year')),
                ('yield_per_10a', models.FloatField(db_column='yield_per_10a')),
                ('total_production', models.FloatField(db_column='total_production')),
            ],
            options={
                'db_table': 'onion_production',
                'managed': False,
            },
        ),
    ]
