# Generated by Django 5.1.6 on 2025-07-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cabbage_onion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabbage',
            options={'managed': True},
        ),
    ]
