# Generated by Django 5.1.6 on 2025-07-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cabbage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabbage',
            options={'managed': False},
        ),
    ]
