# Generated by Django 5.1.6 on 2025-07-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cabbage_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherdata',
            table='climatedata',
        ),
    ]
