# Generated by Django 5.1.6 on 2025-07-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_weatherdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabbage',
            table='cabbagedata',
        ),
        migrations.AlterModelTable(
            name='onion',
            table='oniondata',
        ),
    ]
