# Generated by Django 5.1.6 on 2025-08-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cabbage_table_alter_onion_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureClimate',
            fields=[
                ('main_scenario', models.CharField(db_column='main_scenario', max_length=100, primary_key=True, serialize=False)),
                ('sub_scenario', models.CharField(db_column='sub_scenario', max_length=50)),
                ('year', models.IntegerField(db_column='년')),
                ('month', models.IntegerField(db_column='월')),
                ('sido', models.CharField(db_column='시도', max_length=50)),
                ('sigungu', models.CharField(db_column='시군구', max_length=50)),
                ('eupmyeondong', models.CharField(blank=True, db_column='읍면동', max_length=50, null=True)),
                ('avg_temp', models.FloatField(blank=True, db_column='평균기온', null=True)),
                ('max_temp', models.FloatField(db_column='최고기온')),
                ('min_temp', models.FloatField(db_column='최저기온')),
                ('humidity', models.FloatField(db_column='습도')),
                ('wind_speed', models.FloatField(db_column='풍속')),
                ('avg_precipitation', models.FloatField(db_column='강수량')),
                ('solar_radiation', models.FloatField(db_column='일사량')),
            ],
            options={
                'db_table': 'climate_scenarios',
                'managed': False,
            },
        ),
    ]
